name = "solitaire"
description = "Solitaire card game implemneted in Ada."
version = "0.0.0"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]

executables = ["solitaire"]

[[depends-on]]  # This line was added by `alr with`
sdlada = "^2.5.4-1"  # This line was added by `alr with`
